import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {build,root,shippedFiles,openingFiles} from '../scripts/build.mjs';
import {startStaging} from '../scripts/staging.mjs';
import {TOKEN_A} from './fixtures.mjs';
test('build ships only approved static files, unchanged later photos, no legacy endpoints or synthetic fixtures',async()=>{
 const dist=await build();const files=(await readdir(dist,{recursive:true,withFileTypes:true})).filter(item=>item.isFile()).map(item=>(item.parentPath+'/'+item.name).slice(dist.length+1));assert.deepEqual(files.sort(),[...shippedFiles].sort());
 for(const file of ['assets/photos/story-01.webp','assets/photos/personal-note.webp']){
  const original=execFileSync('git',['show',`HEAD:${file}`],{cwd:root,maxBuffer:2e6});assert.deepEqual(await readFile(`${dist}/${file}`),original);
 }
 for(const file of ['style.css','assets/photos/hero-main.webp']) assert.deepEqual(await readFile(`${dist}/${file}`),await readFile(`${root}/${file}`));
 for(const file of shippedFiles.filter(file=>/\.(js|html)$/.test(file))){const code=await readFile(`${dist}/${file}`,'utf8');assert.ok(!code.includes(TOKEN_A));assert.ok(!/sampleData|AKfycbzO4|confirmedGroupMembers|console\.(log|error|warn)|createTableVisibility/.test(code));}
 const html=await readFile(`${dist}/index.html`,'utf8');assert.ok(html.includes('type="module" src="script.js"'));assert.ok(!/memory-form|member-list|dining-scene/.test(html));
});
test('remote build requires an explicitly valid endpoint and rejects query credentials',async()=>{
 await assert.rejects(build({apiUrl:'https://evil.invalid/'}));await assert.rejects(build({apiUrl:'https://script.google.com/macros/s/example/exec?token=secret'}));
});
test('localhost staging serves actual v2 backend, blocks private files and only mutates memory',async()=>{
 const result=await startStaging({port:0});
 try{
  const send=body=>fetch(result.url+'/api',{method:'POST',body:JSON.stringify(body)}).then(r=>r.json());
  const r=await send({action:'invitation',token:TOKEN_A});assert.equal(r.state,'ready');
  result.setScenario('available');assert.equal((await send({action:'invitation',token:TOKEN_A})).tableCheck.state,'available');
  for(const path of ['apps-script.gs','tests/fixtures.mjs','.git/config','README.md','assets/photos/story-01.JPG'])assert.equal((await fetch(result.url+'/'+path)).status,404);
  const post=await send({action:'rsvp',token:TOKEN_A,requestId:'e'.repeat(32),status:'unable',partySize:null,under5ChildCount:null,dietaryRequirements:'',privateNote:'synthetic only'});assert.equal(post.state,'saved');assert.equal(result.harness.stats.writes.length,1);
  assert.equal((await fetch(result.url+'/api',{method:'POST',headers:{Origin:'https://evil.invalid'},body:'{}'})).status,403);
 }finally{await new Promise(resolve=>result.server.close(resolve));}
});

test('frontend v2 builds an exact independent allowlist without touching the legacy output',async()=>{
 const oldFiles=await Promise.all(shippedFiles.map(async file=>[file,await readFile(`${root}/dist/${file}`)]));
 const dist=await build({frontend:'v2'});
 const files=(await readdir(dist,{recursive:true,withFileTypes:true})).filter(item=>item.isFile()).map(item=>(item.parentPath+'/'+item.name).slice(dist.length+1));
 assert.deepEqual(files.sort(),[...openingFiles].sort());
 for(const file of openingFiles) assert.deepEqual(await readFile(`${dist}/${file}`),await readFile(`${root}/${file}`));
 for(const [file,bytes] of oldFiles) assert.deepEqual(await readFile(`${root}/dist/${file}`),bytes);
 const html=await readFile(`${dist}/frontend-v2/index.html`,'utf8');
 assert.ok(html.includes('../assets/photos/hero-main.webp'));
 assert.ok(html.includes('rel="icon" href="../assets/photos/hero-main.webp"'));
 assert.ok(html.includes('../assets/photos/love-story-8433a-20.jpg'));
 assert.ok(html.includes('styles/page-02.css'));
 assert.ok(html.includes('styles/page-03-04.css'));
 assert.ok(html.includes('styles/page-05.css'));
 assert.ok(html.includes('styles/page-06.css'));
 assert.ok(html.includes('styles/page-07.css'));
 assert.ok(html.includes('styles/motion.css'));
 assert.ok(html.includes('../assets/photos/forever-starts-here-8433a-54.jpg'));
 assert.ok(html.includes('../assets/photos/louis-portrait-8433a-53.jpg'));
 assert.ok(html.includes('../assets/photos/joyce-portrait-8433a-57.jpg'));
 assert.ok(html.includes('../assets/photos/emotional-closing-8433a-113.jpg'));
 assert.ok(html.indexOf('story__content') < html.indexOf('story__figure'));
 assert.ok(html.indexOf('class="forever"') < html.indexOf('class="portraits"'));
 assert.ok(html.indexOf('class="portraits"') < html.indexOf('class="ceremony"'));
 assert.ok(html.indexOf('class="ceremony"') < html.indexOf('class="evening"'));
 assert.ok(html.indexOf('class="evening"') < html.indexOf('class="closing"'));
 assert.match(html,/class="ceremony"[\s\S]*05 · 12 · 2026[\s\S]*6:00 PM[\s\S]*7:00 PM[\s\S]*億家主题宴会厅 · [\s\S]*Hall E[\s\S]*露天草坪[\s\S]*Smart Casual/);
 assert.match(html,/href="https:\/\/maps\.app\.goo\.gl\/tDacdw6Jo4zL5B4U6"[\s\S]*target="_blank"[\s\S]*rel="noopener noreferrer"/);
 assert.ok(!/<section[^>]+class="ceremony"[\s\S]*\bMenu\b[\s\S]*<\/section>/.test(html));
 const ceremonyHtml=html.slice(html.indexOf('<section class="ceremony"'),html.indexOf('</section>',html.indexOf('<section class="ceremony"')));
 assert.equal([...ceremonyHtml.matchAll(/data-reveal=/g)].length,7);
 assert.ok(!/December/i.test(ceremonyHtml));
 const ceremonyCss=await readFile(`${dist}/frontend-v2/styles/page-05.css`,'utf8');
 assert.match(ceremonyCss,/min-height: 100svh/);
 assert.match(ceremonyCss,/\.ceremony__date-display[\s\S]*white-space: nowrap/);
 assert.match(ceremonyCss,/\.ceremony__item--dress dd[\s\S]*font-family: var\(--font-display\)/);
 assert.ok(!/border-radius|box-shadow/.test(ceremonyCss));
 const eveningHtml=html.slice(html.indexOf('<section class="evening"'),html.indexOf('</section>',html.indexOf('<section class="evening"')));
 assert.match(eveningHtml,/\b06\b[\s\S]*The Evening[\s\S]*6:00–7:00 PM[\s\S]*The Ceremony[\s\S]*7:00–8:00 PM[\s\S]*Dinner Begins[\s\S]*8:00–9:00 PM[\s\S]*Celebrate With Us[\s\S]*9:00–10:00 PM[\s\S]*Stay A Little Longer/);
 assert.equal([...eveningHtml.matchAll(/<svg\b/g)].length,4);
 assert.equal([...eveningHtml.matchAll(/class="evening__event"/g)].length,4);
 assert.equal([...eveningHtml.matchAll(/data-reveal="text"/g)].length,6);
 assert.equal([...eveningHtml.matchAll(/data-reveal="timeline-line"/g)].length,1);
 const eveningCss=await readFile(`${dist}/frontend-v2/styles/page-06.css`,'utf8');
 assert.match(eveningCss,/min-height: 100svh/);
 assert.match(eveningCss,/\.evening__line[\s\S]*background: var\(--color-lavender\)/);
 assert.match(eveningCss,/data-reveal="timeline-line"/);
 assert.match(eveningCss,/@media \(prefers-reduced-motion: reduce\)/);
 assert.ok(!/border-radius|box-shadow|scroll-snap/.test(eveningCss));
 const closingHtml=html.slice(html.indexOf('<section class="closing"'),html.indexOf('</section>',html.indexOf('<section class="closing"')));
 assert.match(closingHtml,/\b07\b[\s\S]*The Moment We Say “I Do\.”/);
 assert.match(closingHtml,/src="\.\.\/assets\/photos\/emotional-closing-8433a-113\.jpg" width="2400" height="1600"[\s\S]*alt="Louis and Joyce holding hands by the sea at sunset\."/);
 assert.equal([...closingHtml.matchAll(/data-reveal=/g)].length,3);
 assert.equal([...closingHtml.matchAll(/<h2\b/g)].length,1);
 assert.ok(!/subtitle|caption|monogram|icon/i.test(closingHtml));
 const closingCss=await readFile(`${dist}/frontend-v2/styles/page-07.css`,'utf8');
 assert.match(closingCss,/min-height: 100svh/);
 assert.match(closingCss,/\.closing__photo[\s\S]*object-fit: cover/);
 assert.match(closingCss,/\.closing__statement[\s\S]*left: 50%[\s\S]*text-align: center/);
 assert.match(closingCss,/data-reveal="closing-photo"/);
 assert.match(closingCss,/@media \(prefers-reduced-motion: reduce\)/);
 assert.match(closingCss,/@media \(max-width: 767px\)[\s\S]*\.closing__media::before[\s\S]*background-image: url\("\.\.\/\.\.\/assets\/photos\/emotional-closing-8433a-113\.jpg"\)/);
 assert.match(closingCss,/@media \(max-width: 767px\)[\s\S]*\.closing__photo[\s\S]*height: 64%[\s\S]*object-fit: contain[\s\S]*mask-image:/);
 assert.ok(!/border-radius|box-shadow|scroll-snap|position: sticky/.test(closingCss));
 assert.ok(!/page-08|class="page-08"|data-page="08"/.test(html));
 const chapterCss=await readFile(`${dist}/frontend-v2/styles/page-03-04.css`,'utf8');
 assert.match(chapterCss,/@media \(max-width: 767px\) and \(prefers-reduced-motion: no-preference\)[\s\S]*height: 208svh/);
 assert.match(chapterCss,/position: sticky;[\s\S]*height: 100svh;[\s\S]*overflow: clip/);
 assert.match(chapterCss,/width: 200vw;[\s\S]*translate3d\(var\(--sequence-x, 0px\), 0, 0\)/);
 assert.ok(!/scroll-snap|sequence-peek|forever__progress/.test(chapterCss));
 assert.ok(!html.includes('03 — 04 →'));
 assert.ok(html.includes('scripts/editorial-sequence.js'));
 const sequenceJs=await readFile(`${dist}/frontend-v2/scripts/editorial-sequence.js`,'utf8');
 assert.match(sequenceJs,/requestAnimationFrame/);
 assert.match(sequenceJs,/passive: true/);
 assert.ok(!/preventDefault|touchmove|wheel/.test(sequenceJs));
 const motionCss=await readFile(`${dist}/frontend-v2/styles/motion.css`,'utf8');
 const revealJs=await readFile(`${dist}/frontend-v2/scripts/reveal.js`,'utf8');
 assert.match(motionCss,/\.reveal-ready \[data-reveal="text"\]:not\(\.is-revealed\)/);
 assert.match(motionCss,/@media \(max-width: 767px\)[\s\S]*data-reveal="story-photo"/);
 assert.match(motionCss,/@media \(min-width: 768px\)[\s\S]*data-reveal="portrait-left"/);
 assert.match(motionCss,/@media \(prefers-reduced-motion: reduce\)/);
 assert.match(revealJs,/new IntersectionObserver/);
 assert.match(revealJs,/threshold: 0\.18/);
 assert.match(revealJs,/observer\.unobserve/);
 assert.ok(!/scroll|requestAnimationFrame|preventDefault/.test(revealJs));
 assert.ok(!html.slice(0,html.indexOf('<section class="story"')).includes('data-reveal'));
 assert.ok(html.includes('scripts/reveal.js'));
 assert.ok(!/animation-timeline/.test(chapterCss));
 assert.ok(!/rsvp|table-check|js\/api|src="script.js"|href="style.css"/.test(html));
 await assert.rejects(build({frontend:'v2',apiUrl:'https://script.google.com/macros/s/example/exec'}));
 await assert.rejects(build({frontend:'unknown'}));
});
test('frontend v2 serves only public invitation assets with no API or writable routes',async()=>{
 const result=await startStaging({frontend:'v2',port:0});
 try {
  const response=await fetch(result.url+'/');assert.equal(response.status,200);assert.equal(new URL(response.url).pathname,'/frontend-v2/');
  assert.match(response.headers.get('content-security-policy'),/connect-src 'none'/);
  const html=await response.text();assert.ok(html.includes('Louis Ng'));
  const localAssets=[...html.matchAll(/(?:href|src)="([^"]+)"/g)].map(match=>match[1]).filter(value=>!value.startsWith('https://'));
  for(const asset of localAssets) assert.equal((await fetch(new URL(asset,response.url))).status,200,asset);
  const githubPagesBase=new URL('https://example.invalid/wedding-invitation/frontend-v2/');
  assert.equal(new URL('styles/page-02.css',githubPagesBase).pathname,'/wedding-invitation/frontend-v2/styles/page-02.css');
  assert.equal(new URL('styles/page-03-04.css',githubPagesBase).pathname,'/wedding-invitation/frontend-v2/styles/page-03-04.css');
  assert.equal(new URL('styles/page-05.css',githubPagesBase).pathname,'/wedding-invitation/frontend-v2/styles/page-05.css');
  assert.equal(new URL('styles/page-06.css',githubPagesBase).pathname,'/wedding-invitation/frontend-v2/styles/page-06.css');
  assert.equal(new URL('styles/page-07.css',githubPagesBase).pathname,'/wedding-invitation/frontend-v2/styles/page-07.css');
  assert.equal(new URL('../assets/photos/emotional-closing-8433a-113.jpg',githubPagesBase).pathname,'/wedding-invitation/assets/photos/emotional-closing-8433a-113.jpg');
  assert.equal(new URL('../assets/photos/love-story-8433a-20.jpg',githubPagesBase).pathname,'/wedding-invitation/assets/photos/love-story-8433a-20.jpg');
  assert.equal(new URL('../assets/photos/forever-starts-here-8433a-54.jpg',githubPagesBase).pathname,'/wedding-invitation/assets/photos/forever-starts-here-8433a-54.jpg');
  for(const file of openingFiles) assert.equal((await fetch(result.url+'/'+file)).status,200,file);
  for(const file of ['apps-script.gs','tests/fixtures.mjs','tests/harness.mjs','.git/config','.env','index.html','script.js','js/config.js','assets/photos/hero-main.jpg','api','_staging','_staging/stats']) assert.equal((await fetch(result.url+'/'+file)).status,404,file);
  assert.equal((await fetch(result.url+'/api',{method:'POST',body:'{}'})).status,405);
  assert.equal((await fetch(result.url+'/frontend-v2/',{headers:{Origin:'https://example.invalid'}})).status,403);
 } finally {await new Promise(resolve=>result.server.close(resolve));}
});
